
# log
logging:
  file: web-frame.log
  path: F:\\GitHub\\log\\gateway-frame

# 数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web-frame?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    # 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 10
    minIdle: 30
    maxActive: 100
    maxWait: 3000
    removeAbandonedTimeout: 180
    validationQuery: select 1 from dual
  # reids
  redis:
    database: 0
    host: 120.78.142.208
    port: 6379
    password: 123456
    timeout: 2000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
  freemarker:
    checkTemplateLocation: false
  # 邮箱配置
  mail:
    username: 2659471464@qq.com
    password: ijxmrdmxhhecdjai
    default-encoding: UTF-8
    host: smtp.qq.com
    port: 465

# myBatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml

# jwt configuration
jwt:
  secret: MySecret
  header: Authorization
  tokenHeader: LCN
  expiration: 3600
  route:
    authentication:
      path: /auth/**
      refresh: refresh
      register: /auth/register
