
# log
logging:
  file: web-frame.log
  path: F:\\GitHub\\log\\gateway-frame

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web-frame?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath*:mapper/*.xml

# jwt configuration
jwt:
  secret: MySecret
  header: Authorization
  tokenHeader: LCN
  expiration: 3600
  route:
    authentication:
      path: /auth/**
      refresh: refresh
      register: /auth/register

